apiVersion: v1
kind: Service
metadata:
  name: pgsql
spec:
  ports:
    -
      name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector: {}
---
apiVersion: v1
kind: Endpoints
apiVersion: v1
metadata:
  name: pgsql
subsets:
  -
    addresses:
      -
        ip: 192.168.0.34
    ports:
      -
        port: 5432
        name: pgsql