apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgdatabases.my.local
spec:
  group: my.local
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                server:
                  type: string
                db:
                  type: object
                  properties:
                    name:
                      type: string
  names:
    kind: PgDatabase
    singular: pgdatabase
    plural: pgdatabases
  scope: Cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pg-kopf-controller
rules:
  - apiGroups: 
    - my.local
    resources: 
    - pgdatabases
    - pgdatabases/status
    verbs:
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create