apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pg-kopf-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pg-kopf-controller
subjects:
  - kind: ServiceAccount
    namespace: default
    name: pg-kopf-controller